### ISSUE TITLE
Pregunta

### ISSUE THREAD

**Issue by drtino7** [Icesito68/Port-Windows-11-Poco-X3-pro#1]
Los comandos de termux y twrp,ambs deben de realizarce o con uno estaría más que suficiente?

**Comment by Icesito68** [comment]
Es necesario realizar ambos

**Comment by drtino7** [comment]
Cuál primero?

**Comment by Icesito68** [comment]
Los de termux se hacen primero

**Comment by drtino7** [comment]
Me da este error: 

.../files/home # sfdisk -d /dev/block/sda > /sdcard/sda.part
bash:  /sdcard/sda.part: No such file or directory

**Comment by Icesito68** [comment]
Exportaste primero el archivo?
Osea seguiste todos los comandos en orden?
Me acabo de dar cuenta y,¿Estas como superusuario?

**Comment by drtino7** [comment]
Sisi ya lo solucione, muchas gracias, donde se pone la descarga de Windows 11, osea termino los comandos de twrp y que hago?

**Comment by Icesito68** [comment]
debes descargar la imagen de windows 11 para arm, en uup dump la puedes encontrar

**Comment by drtino7** [comment]
Sisi pero que hago con la descarga?

**Comment by Icesito68** [comment]
esos comandos aun no se han subido ya que están pendientes de obtenerse con claridad
aun asi puedes probar
Instalar Windows en el poco x3
dism /apply-image /ImageFile:"C:\Users\Usuario\Downloads\Carpetadewindowsarm\sources\install.wim" /index:1 /ApplyDir:X:\

**Comment by drtino7** [comment]
Ah genial!!! Muchísimas gracias por la paciencia estoy al tanto :)

**Comment by Icesito68** [comment]
un gusto poder ayudar, aun asi echale un ojo a lo que te acabo de compartir,con eso puedes instalar windows 11, luego solo queda poder ponerle los drivers que tenemos hasta el momento

**Comment by drtino7** [comment]
Que deberia hacer con eso copiarlo y pergarlo en twrp, o en Powershell?

**Comment by Icesito68** [comment]
si no recuerdo mal era en un CMD pero con permisos de administrador (shift+ctrl+enter)

**Comment by drtino7** [comment]
Muchas gracias!! Llego a mí casa y pruebo

**Comment by Icesito68** [comment]
perfecto,espero que te funcione

**Comment by drtino7** [comment]
Ahora buen una vez que terminó los comandos del twrp y flasheo el UEFI que va a pasar? Bootea en win pe?

**Comment by Icesito68** [comment]
no, aqui no se usa windows pe, aun quedan los drivers para instalar los drivers para que windows pueda iniciar

**Comment by drtino7** [comment]
Y los drivers existentes,para la instalación de win, cómo se instalan?

**Comment by Icesito68** [comment]
también queda subir esos comandos, ten en cuenta que aún se están reuniendo todos para poder subirlos en orden y de manera correcta

**Comment by drtino7** [comment]
Hola buenas no estaría entendiendo esta parte: 



#Le asignamos la letra y al volumen donde instalaremos los drivers  
 assign letter=y  
   
 #Instalar Windows 11 en el X3 Pro (sustituir "Usuario" por tu usuario y "Carpetadewindowsarm"por tu carpeta que contiene windows arm,importante que sea sin espacios)  
 dism /apply-image /ImageFile:"C:\Users\Usuario\Downloads\Carpetadewindowsarm\sources\install.wim" /index:1 /ApplyDir:X:\   
   
 #Instalar drivers (sustituir mipad5folder por la ubicacion de la carpeta de los drivers)(abrir en powershell como administrador)  
 .\driverupdater.exe -d (mipad5folder)\definitions\Desktop\ARM64\Internal\vayu.txt -r (mipad5folder) -p X:```  
   
 #Ahora se tienen que permitir los drivers no firmados  
 bcdboot X:\Windows /s Y: /f UEFI  
   
 bcdedit /store Y:\EFI\Microsoft\BOOT\BCD /set {default} testsigning on  
   
 bcdedit /store Y:\EFI\Microsoft\BOOT\BCD /set {bootmgr} displaybootmenu yes 

No entiendo las letras

**Comment by Icesito68** [comment]
hace falta asignarle letras para que windows los reconozca como disco,o que parte más exactamente no entiendes?

**Comment by drtino7** [comment]
Osea sería el disco duro "D " por ejemplo?

**Comment by Icesito68** [comment]
mas o menos si, pero hay que asignarles esas letras por tema drivers

**Comment by drtino7** [comment]
Genial... Tengo un problema con la descarga de win 11, como sería la misma, que debo de seleccionar  ya que se me descargo la .iso no el archivo install.wim

**Comment by Icesito68** [comment]
si no recuerdo mal hay que extraer el .iso, winrar puede administrar eso perfectamente

**Comment by drtino7** [comment]
Genial una vez que tengo todos los archivos,te agradezco por la paciencia, y de nuevo te molesto no termino de entender la parte de formatear, escribo los comandos en el twrp? Y luego dice así:

#formatear desde TWRP, en la línea 50

Esto significa que debo formatear el móvil? Un factory reset? O es solo los comandos anteriores?


Y además una vez terminado los comandos de termux puedo borrar el módulo?

**Comment by Icesito68** [comment]
Necesitas formatear android, exacto, para poder usarlo ya que al borrar y crear de nuevo la partición no arrancará por el sistema de archivos que se usa, por eso tienes que formatear desde twrp ( la opción en la q tienes que poner ("yes")
Y si, ya no es necesario el módulo, siquiera tienes que seguir siendo root
