### ISSUE TITLE
Drivers 

### ISSUE THREAD

**Issue by madoolex** [Icesito68/Port-Windows-11-Poco-X3-pro#11]
Hello dude.
Installing windows drivers is easy?i mean we can do it through the windows (like windows update) or have too do special thing?
As i knew the important part of this project is inalling windows.then i can install drivers which you release. Is that right?
And i ask you for a full english tutorial using the phone.im not sure i can do it now.cause will probably brick my phone :))
Thanks for everything

**Comment by Icesito68** [comment]
unfortunately I can't do a tutorial in English, I'm Spanish it's difficult for me
and the drivers it is better to install them before starting windows, otherwise it will not work, it will always be done with the commands, even to update

**Comment by ahmeda9a** [comment]
> Hello dude. Installing windows drivers is easy?i mean we can do it through the windows (like windows update) or have too do special thing? As i knew the important part of this project is inalling windows.then i can install drivers which you release. Is that right? And i ask you for a full english tutorial using the phone.im not sure i can do it now.cause will probably brick my phone :)) Thanks for everything

you must install the drivers using the driverupdater from your pc every time. windows update cannot do that for you. dont worry though, you dont have to start the whole process again, only certain ones and doesnt include formating and repartitioning.
