### ISSUE TITLE
Powered hub

### ISSUE THREAD

**Issue by ahmeda9a** [Icesito68/Port-Windows-11-Poco-X3-pro#13]
Can this be fixed later? Needing a powered hub means that we have to always be near a charger and we can't use it as mobile.

**Comment by halal-beef** [comment]
This is an issue related with something named chargerpd, it'll be very hard to fix but some time in the future it might be

**Comment by ahmeda9a** [comment]
Thanks for clarifying, it is really needed though since we also can't use touch
