### ISSUE TITLE
[QUESTION] - Partition scheme fried

### ISSUE THREAD

**Issue by wasab1i** [Icesito68/Port-Windows-11-Poco-X3-pro#14]
### Description

Please, send me the poco x3 pro partition scheme, i cannot boot android anymore

### Reproduction steps

```bash
a
```

### Agreement

- [ ] I am using the latest Drivers.
- [ ] I am running Windows 11 On The Phone.
- [x] There is no issue already describing my problem.

**Comment by madoolex** [comment]
Hi.Bro i have some questions. can you send me a message in telegram pls?

**Comment by Icesito68** [comment]
reinstall the rom and format from twrp, if not flash with my flash

**Comment by wasab1i** [comment]
where can i find your flash

**Comment by wasab1i** [comment]
> Hi.Bro i have some questions. can you send me a message in telegram pls? @Madooolex

ok

**Comment by Icesito68** [comment]
Xiaomi mi flash,the oficial tool for flash devices

**Comment by wasab1i** [comment]
ok flashing the rom let me boot the firmware, but now, if i want to flash the recovery, adb says that there is no recovery partition

**Comment by wasab1i** [comment]
FAILED (remote: (recovery) No such partition)

**Comment by Icesito68** [comment]
No used remote recovery,try fastboot flash recovery (recovery.img)

**Comment by wasab1i** [comment]
> No used remote recovery,try fastboot flash recovery (recovery.img)

fastboot flash recovery C:\Users\wasab\Downloads\twrp-3.7.0_12-0-vayu.img
target reported max download size of 805306368 bytes
sending 'recovery' (131072 KB)...
OKAY [  2.829s]
writing 'recovery'...
FAILED (remote: (recovery) No such partition)
finished. total time: 2.837s

**Comment by Icesito68** [comment]
Hmmm,try use my flash tool

**Comment by wasab1i** [comment]
![Immagine 2022-10-23 220623](https://user-images.githubusercontent.com/103177455/197415667-5cb1d90c-847d-481f-9c8c-c9d9652ff189.png)

**Comment by Icesito68** [comment]
Ouh this is really weird

**Comment by Icesito68** [comment]
Fastboot boot (twrp.img)

**Comment by wasab1i** [comment]
> Fastboot boot (twrp.img)

yes doing this make me boot into recovery, but is not installed

**Comment by Icesito68** [comment]
Dont worry,you don't need to have recovery installed

**Comment by Icesito68** [comment]
You only try

**Comment by ahmeda9a** [comment]
He might accidentally deleted the recovery from the partition table or parted. Mi flash doesnt repartition the device and thus cannot fix it (i tried, windows 11 and all the partitions were unchanged after using mi flash)

**Comment by ahmeda9a** [comment]
He will need to use parted or disk tools(disk tools i think, i dont think he deleted the partition from parted) then edit it.

**Comment by wasab1i** [comment]
> He will need to use parted or disk tools(disk tools i think, i dont think he deleted the partition from parted) then edit it.

how can i reimport the partition?

**Comment by ahmeda9a** [comment]
Not really sure how can i make you a tutorial. But basically we will need to give you our partition table so you can put it in place of yours using some commands from termux section. im waiting for a dev to confirm that it will work.

**Comment by halal-beef** [comment]
You'll have to use parted in twrp to rebuild ur partition map

**Comment by ahmeda9a** [comment]
This will take time,  @Icesito68 do you have a file with your current partition table? I cannot get mine currently.

 @wasab1i we will need your partition table too so we can check whats wrong. You can bring it up by running "print all" when parted is running

**Comment by wasab1i** [comment]
> This will take time,  @Icesito68 do you have a file with your current partition table? I cannot get mine currently.
> 
>  @wasab1i we will need your partition table too so we can check whats wrong. You can bring it up by running "print all" when parted is running 

Ok seems good

**Comment by halal-beef** [comment]
Has ur partition table been restored? Cause this issue will be closed for lack of communication

**Comment by wasab1i** [comment]
> You'll have to use parted in twrp to rebuild ur partition map

Guys sorry for no response, i got the partition scheme from a good one

**Comment by wasab1i** [comment]
how can i flash it

**Comment by wasab1i** [comment]
Disk /dev/block/sda: 497303552 sectors, 1088M
Logical sector size: 4096
Disk identifier (GUID): c9b07318-ce20-cf8c-4efa-8be5630891f5
Partition table holds up to 32 entries
First usable sector is 6, last usable sector is 62162938

Number Start (sector) End (sector) Size Name
1 6 7 8192 switch
2 8 15 32768 ssd
3 16 23 32768 dbg
4 24 31 32768 bk01
5 32 63 128K bk02
6 64 127 256K bk03
7 128 255 512K bk04
8 256 383 512K keystore
9 384 511 512K frp
10 512 1023 2048K countrycode
11 1024 2047 4096K misc
12 2048 3071 4096K vm-data
13 3072 4095 4096K bk06
14 4096 6143 8192K logfs
15 6144 8191 8192K ffu
16 8192 12287 16.0M oops
17 12288 16383 16.0M devinfo
18 16384 20479 16.0M oem_misc1
19 20480 24575 16.0M metadata
20 24576 32603 31.3M bk08
21 32604 40959 32.6M splash
22 40960 49151 32.0M bk09
23 49152 2277375 8704M super
24 2277376 2293759 64.0M logdump
25 2293760 2326527 128M minidump
26 2326528 2359295 128M rawdump
27 2359296 2359807 2048K imagefv
28 2359808 2392575 128M recovery
29 2392576 2490879 384M cache
30 2490880 2589183 384M exaid
31 2589184 2851327 1024M cust
32 2851328 62162938 226G userdata

**Comment by Icesito68** [comment]
that's not good at all, you have to edit it yourself, you can't take the one from another device, also that still has the 32 partitions

**Comment by wasab1i** [comment]
(parted) print all
print all
Error: /dev/block/sda: unrecognised disk label

**Comment by wasab1i** [comment]
my parted says this to print all

**Comment by wasab1i** [comment]
how can i do mkpart recovery

**Comment by Icesito68** [comment]
I don't quite understand what is happening or the question

**Comment by wasab1i** [comment]
Ok, sorry, the problem is that if I try to do print all, parted says Error: /dev/block/sda: unrecognised disk label

**Comment by Icesito68** [comment]
make sure you have unmounted the storage and passed parted correctly

**Comment by wasab1i** [comment]
i think that all of my partiton are fried

**Comment by wasab1i** [comment]
but i didn't do anything

**Comment by wasab1i** [comment]
other than opening parted

**Comment by Icesito68** [comment]
android works?

**Comment by wasab1i** [comment]
no

**Comment by wasab1i** [comment]
neither flashing it

**Comment by Icesito68** [comment]
did you try to reinstall android with mi flash?

**Comment by wasab1i** [comment]
elapse 0s, error

**Comment by wasab1i** [comment]
oh wait

**Comment by Icesito68** [comment]
you can contact them at the following link, they are in charge of reviving xiaomi mobiles, if you tell them that you are on behalf of special ice they will give you a discount
 https://t.me/EDLautorizadoxiaomi

**Comment by halal-beef** [comment]
Actually, edl won't be needed he just did the commands wrong, in parted u just type print

**Comment by halal-beef** [comment]
I'll print mine and compare to urs later and tell u the commands needed to fix

**Comment by wasab1i** [comment]
thank you so much

**Comment by halal-beef** [comment]
@wasab1i is your device the 8/256gb device

**Comment by wasab1i** [comment]
yes it is

**Comment by halal-beef** [comment]
i have a weird idea, can you do fast boot reboot edl and install edl drivers, then use mi flash tool

**Comment by wasab1i** [comment]
fastboot: usage: unknown reboot target edl

**Comment by halal-beef** [comment]
try adb reboot edl (from twrp)

**Comment by halal-beef** [comment]
okay i got the fast boot command


fastboot oem edl

**Comment by wasab1i** [comment]
I'm in edl

**Comment by halal-beef** [comment]
okay great, do u have drivers installed

**Comment by halal-beef** [comment]
[QDLoader HS-USB Driver_64bit_Setup.exe.zip](https://github.com/Icesito68/Port-Windows-11-Poco-X3-pro/files/9943950/QDLoader.HS-USB.Driver_64bit_Setup.exe.zip)

here are drivers, unzip and install then u should be able to start restoring

**Comment by wasab1i** [comment]
miflash is asking for a mi account

**Comment by halal-beef** [comment]
that's strange, mi flash usually doesnt need auth if on unlocked boot loader

**Comment by wasab1i** [comment]
it says he needs it for edl auth

**Comment by wasab1i** [comment]
and that my account doesn't have permission

**Comment by halal-beef** [comment]
Well, I guess u need Auth

**Comment by wasab1i** [comment]
but how

**Comment by wasab1i** [comment]
it gives me an error of auth

**Comment by halal-beef** [comment]
You'll have to probably contact the telegram group, partition table too fried beyond repair

**Comment by wasab1i** [comment]
what do i need to say in the group

**Comment by wasab1i** [comment]
Ok, great, i tried to contact xiaomi for the warranty, In 3 days they will pick up the phone and if they can't fix it they'll give me a new one for free

**Comment by wasab1i** [comment]
stonks

**Comment by Icesito68** [comment]
Yeah

**Comment by halal-beef** [comment]
alright, that's good please dont screw it up again tho, I'm sure that's already cost you enough.

**Comment by wasab1i** [comment]
> alright, that's good please dont screw it up again tho, I'm sure that's already cost you enough.

yeah I think so, thank you guys so much for everything
