### ISSUE TITLE
Partition sizes

### ISSUE THREAD

**Issue by ahmeda9a** [Icesito68/Port-Windows-11-Poco-X3-pro#2]
Can we choose our own partition sizes to make windows space bigger?

Also, where is parted file? Is it included with the platform tools?

**Comment by drtino7** [comment]
The parted file idownloaded from that video:https://youtu.be/CaQ9B6IGIjg

From the description in essentials file

**Comment by Icesito68** [comment]
you can make windows as big as you want, however if something goes wrong you can brick the device, only do it if you are sure

**Comment by ahmeda9a** [comment]
> you can make windows as big as you want, however if something goes wrong you can brick the device, only do it if you are sure

I think i could break my phone regardless of how much size im giving to windows. So if there isnt any direct harm for making custom sizes, can we have a separate tutorial for that? It kinda looks easy when i look at the commands but i just want to be sure of what im doing.

**Comment by Icesito68** [comment]
there will be a tutorial as soon as possible, I recommend that you wait to make sure that nothing goes wrong

**Comment by ahmeda9a** [comment]
Somewhat unrelated, but lines 11 and 23 in English twrp commands are written partitioned instead of parted.

**Comment by Icesito68** [comment]
true, there were problems with the translation, thank you very much for letting me know, I'll correct it in a moment
