### ISSUE TITLE
Error SOC_SUBSYSTEM_FAILURE BSOD

### ISSUE THREAD

**Issue by davidgrigoryan163** [Icesito68/Port-Windows-11-Poco-X3-pro#28]
### Question

I very often when I start Windows I have for some time when the phone heats up appears BSOD  with an error SOC_SUBSYSTEM_FAILURE
How to solve this problem? Maybe a problem with the drivers ?

Phone: Poco X3 PRO 
### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [x] There is no issue already describing my problem.

**Comment by davidgrigoryan163** [comment]
It's on the phone Poco X3 PRO

**Comment by halal-beef** [comment]
Issue closed due to staleness, if u do encounter issues with drivers we can talk in tg group

**Comment by davidgrigoryan163** [comment]
I already solved the problem! This was due to the fact that I first installed the old drivers, and then installed the new ones from telegram.

**Comment by halal-beef** [comment]
Glad to see it's solved!
