### ISSUE TITLE
windows sim1,No service?

### ISSUE THREAD

**Issue by XING007X** [Icesito68/Port-Windows-11-Poco-X3-pro#29]
### Question

What should I do?

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by halal-beef** [comment]
Provision modem

**Comment by XING007X** [comment]
> 调制解调器



> 


> Provision modem

how to do？

**Comment by XING007X** [comment]
> Provision modem

Excuse me? How to do?
