### ISSUE TITLE
Dual boot

### ISSUE THREAD

**Issue by ahmeda9a** [Icesito68/Port-Windows-11-Poco-X3-pro#3]
Are we supposed to reach dual boot eventually? So far, it seems that we will have to flash boot partition everytime to switch between windows and android (which requires a PC to execute fastboot commands). Did i miss something?

**Comment by Icesito68** [comment]
if you have the uefi.img in the phone you can flash it from twrp in boot and thus boot in windows without the need of a pc, but remember first to make a backup of the original boot

**Comment by ahmeda9a** [comment]
What about booting to android?

**Comment by ahmeda9a** [comment]
We can just boot to twrp and flash windows UEFI/android boot image to switch between them?

**Comment by Icesito68** [comment]
I just said it, you make a backup, when you want to boot android you just restore it from twrp
the copy would be from the boot partition

**Comment by Icesito68** [comment]
Exactly, it is about flashing the boot image you want in the boot partition

**Comment by ahmeda9a** [comment]
Ohh, nice. It is easy then.

**Comment by Icesito68** [comment]
yep
