### ISSUE TITLE
Symbolic Link error

### ISSUE THREAD

**Issue by Endermen993** [Icesito68/Port-Windows-11-Poco-X3-pro#31]
### Question

I followed all steps and then when I typed msc.sh this error came and only the windows and not the boot loader volume was mounted to my pc. I tried removing mass_storage.0 but it keeps coming back. And then the error comes back. 

 I ll be thankful for any solution.

![2EFAE89D-CD81-4473-94B6-72CB5759E8EB](https://user-images.githubusercontent.com/122880656/212890672-81f31a95-80ab-401b-830b-b24bec86177b.jpeg)

### Agreement

- [ ] I am asking a sensible question.
- [ ] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by halal-beef** [comment]
Don't run MSC twice

**Comment by Endermen993** [comment]
I only ran it twice because the first time only one volume got mounted!

**Comment by halal-beef** [comment]
Of course first volume will get mounted!! The esp partiton is set as as a system reserved partiton so it'll be hidden!!!! That's why we assign letters!!!!!!!!!!!!!!!!!!!
