### ISSUE TITLE
error en umount /data && umount /sdcard

### ISSUE THREAD

**Issue by drtino7** [Icesito68/Port-Windows-11-Poco-X3-pro#4]
me da un error:

umount: /data: invalid argument

**Comment by Icesito68** [comment]
No te preocupes,suele pasar, puedes continuar perfectamente

**Comment by drtino7** [comment]
hola... e tenido un par de problemillas:
cunado puse estos comandos: 
mkfs.fat -F32 -s1 /dev/block/by-name/esp

mkfs.ntfs -f /dev/block/by-name/win
me salto que no exixtian estos directorios y cuando quise formatear me puso:

unable to mount storage

despues entre de nuevo a a parted le di un print list y no existian mas los directorios

que puedo hacer aparte de flashearlo?

**Comment by Icesito68** [comment]
Es normal que salgan errores a la hora de hacer eso, sin embargo asegúrate de ejecutar parted correctamente, volviendo a aplicar los mismos comandos

**Comment by drtino7** [comment]
y que hago flasheo?

**Comment by drtino7** [comment]
ya que android no me inicia

**Comment by Icesito68** [comment]
Prueba a reinstalar la ROM, yo tuve que hacerlo, ahí quizás si te deja formatear las particiones

**Comment by drtino7** [comment]
ok... pruebo

**Comment by Icesito68** [comment]
Tranquilo que no perderás las particiones de Windows

**Comment by drtino7** [comment]
si formateo no las pierdo?

**Comment by Icesito68** [comment]
Formateando desde twrp no pierdes las particiones de Windows

**Comment by drtino7** [comment]
igualmente que pudo haber pasado, ya que no podia formatear las particiones de windows, no se habran creado?

una vez reinstale la rom que debo hacer? debo rehacer los comandos en termux, los comandos de parted?

**Comment by Icesito68** [comment]
No, no debes rehacer ningún comando, y ya te dije que esos errores son normales hasta donde recuerdo,tecnicamente si deberían haberse formateado y estar todo correctamente

**Comment by drtino7** [comment]
genial... gracias actualmente le reinstale la rom y no quiere formatear voy a ver q puedo hacer

**Comment by Icesito68** [comment]
Como digo, no tienes que formatear de nuevo, son errores comunes,realmente si se realizó la operación, puedes seguir con el proceso

**Comment by drtino7** [comment]
yaya pero no me inicia android

**Comment by drtino7** [comment]
se queda en la boot animation de la rom

**Comment by Icesito68** [comment]
Ah, entendí mal entonces, trata de borrar manualmente las particiones de system,data,internal storage,caché y dalvik, luego reinstala la rom

**Comment by drtino7** [comment]
me da error

**Comment by Icesito68** [comment]
Pues prueba a instalar una ROM de android 11,las cuales no encriptan el almacenamiento,ya después vuelves a una de android 12 o 13

**Comment by Icesito68** [comment]
La instalas,apagas,vuelves al recovery y formateas

**Comment by drtino7** [comment]
de echo estoy con arrow os 11

**Comment by drtino7** [comment]
supongo que voy a cambir a orange fox ya que me desencriptaba

**Comment by drtino7** [comment]
no me desencripta por ningun motivo que hago?

**Comment by Icesito68** [comment]
Pues la única que te queda es usar el mi flash con miui stock y luego volver a cambiar de rom,supongo

**Comment by drtino7** [comment]
hola buenas no me flashe el userdata.img, ya no c que hacer probe de todo e incluso no me reconoce el adb,tienes idea de que puedo hacer?

**Comment by Icesito68** [comment]
es que realmente no tengo ni idea,yo reinstalé la rom y formatee y todo se solucionó, prueba a hacerlo con el mi flash,es la que te queda

**Comment by ahmeda9a** [comment]
Not Spanish but was using translation, assuming he got to the point where he deleted partitions, is using mi flash to go back to stock safe?

**Comment by Icesito68** [comment]
my flash can be used in case something goes wrong, however if you delete the partitions wrong even that won't save it

**Comment by drtino7** [comment]
sisi nada no quiere, lo voy a llevar a arreglar

**Comment by Icesito68** [comment]
Pues una pena la verdad, es extraño,de alguna manera debería haberse solucionado
