### ISSUE TITLE
[BUG] - <Touch issue>

### ISSUE THREAD

**Issue by SSnack1992** [Icesito68/Port-Windows-11-Poco-X3-pro#42]
### Description

Hey I have a problem with the touchscreen Windows 11 runs quite well but I can only get to the screen where I am supposed to enter my WLAN password, but that is an impossibility... to understand it works about 1 third of the screen  from the top, everything is mirrored and rotated.. so I can't enter the password of the WLAN router... Did any of you have a similar problem?

### Reproduction steps

```bash
Install Win 11
```

### Agreement

- [X] I am using the latest Drivers.
- [X] I am running Windows 11 On The Phone.
- [X] There is no issue already describing my problem.

**Comment by Icesito68** [comment]
Are you sure you have chosen the correct uefi and driver for the panel you have?

**Comment by SSnack1992** [comment]
I have a Tianma device... but I didn't know whether I should take 6gb or 8gb... I then decided on the 8gb version... I can't imagine that something went wrong with the driver installation.  It went through without an error message... what should I do now?

**Comment by halal-beef** [comment]
You are literally wasting our time, it's literally listed in the trouble shooting section. Maybe check that before opening and issue
