### ISSUE TITLE
[BUG] - Wi-Fi: Oops, you've lost connection

### ISSUE THREAD

**Issue by zoeleu** [Icesito68/Port-Windows-11-Poco-X3-pro#43]
### Description

Windows setup cannot proceed because it says "you've lost internet connection"

### Reproduction steps

```bash
1. Boot into fresh Windows 11
2. Proceed with setup
3. Try to connect to WiFi
```

### Agreement

- [X] I am using the latest Drivers.
- [X] I am running Windows 11 On The Phone.
- [X] There is no issue already describing my problem.

**Comment by elestopa** [comment]
One way to get past the setup is to keep trying and reconnecting several times, then get connected and do the updates.

**Comment by zoeleu** [comment]
I can't test this since I bricked my phone. Guess I'm paying 35$ to some sketchy EDL guy now.

**Comment by halal-beef** [comment]
U can bypass this via the accessibility keyboard and oobe bypassnro, will add into troubleshooting l8r
