### ISSUE TITLE
[BUG] - RemoveOfflineDriver: ntStatus=0x80070490

### ISSUE THREAD

**Issue by maldinipunisher** [Icesito68/Port-Windows-11-Poco-X3-pro#45]
### Description

hi how to solve this problem?

### Reproduction steps

```bash
1. go to recovery and run msc.sh
2. user driverupdater.exe and run steps as the tutorial
3. running half then when uninstall some driver i got this error RemoveOfflineDriver: ntStatus=0x80070490
```

### Agreement

- [X] I am using the latest Drivers.
- [X] I am running Windows 11 On The Phone.
- [X] There is no issue already describing my problem.

**Comment by halal-beef** [comment]
Unfortunately you have to reinstall windows

**Comment by aer-i** [comment]
I had the same problem. I just reinstalled windows
