### ISSUE TITLE
[QUESTION] - It works on redmi note 10 pro

### ISSUE THREAD

**Issue by guthubas** [Icesito68/Port-Windows-11-Poco-X3-pro#49]
### Question

It works on Redmi Note 10 Pro because they have the same processor 

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by Icesito68** [comment]
As far as I know, the Redmi Note 10 Pro has 732g, so no, it's not going to work.
