### ISSUE TITLE
Powered USB hub?

### ISSUE THREAD

**Issue by ahmeda9a** [Icesito68/Port-Windows-11-Poco-X3-pro#6]
What does that mean? Can i not use normal USB hubs for just keyboard and mouse?

**Comment by Icesito68** [comment]
you need the hub to have external power to that of the x3 pro

**Comment by ahmeda9a** [comment]
What about OTG for wireless keyboard and mouse adapter?

**Comment by Icesito68** [comment]
I also do not think it will work since you will still need external power

**Comment by ahmeda9a** [comment]
Can you recommend a usb hub that has that feature?

**Comment by Icesito68** [comment]
This
https://a.aliexpress.com/_mLvdOyU

**Comment by ahmeda9a** [comment]
is it possible for us to be able to use normal USB hubs (non external powered) in the future?

**Comment by Icesito68** [comment]
maybe, but we would have to work on it

**Comment by ahmeda9a** [comment]
I guess i will wait then, that USB hub cant be delivered to my country and we dont have such tech available for purchase in our local market.

**Comment by Icesito68** [comment]
a pity the truth, you can try to look for alternatives, but for now we only have that
