### ISSUE TITLE
Installing drivers?

### ISSUE THREAD

**Issue by ahmeda9a** [Icesito68/Port-Windows-11-Poco-X3-pro#8]
How exactly we install the drivers? Do we just download the whole mipad5 drivers source then unzip DriverUpdater.zip in the same folder then run that command or did i miss something?

**Comment by Icesito68** [comment]
driver updater must be on the desktop directly, while the drivers inside the xiaomipad folder, and you must locate the console on the desktop

**Comment by ahmeda9a** [comment]
So we should download the source right?

**Comment by Icesito68** [comment]
you have to download as zip and then unzip both, yep

**Comment by ahmeda9a** [comment]
When drivers get updates, can we install them the same way as the old one? No format required?

**Comment by Icesito68** [comment]
they can be installed in the same way without formatting, just remember to repeat the process of allowing unsigned drivers

**Comment by ahmeda9a** [comment]
Aight, understood. Thank you so much!

**Comment by Icesito68** [comment]
thank you, good luck with the installation
