### ISSUE TITLE
Windows arm

### ISSUE THREAD

**Issue by ahmeda9a** [Icesito68/Port-Windows-11-Poco-X3-pro#9]
When i downloaded windows arm, i chose the option to "include updates" then ran the script. The result was an ISO file(which i will extract the files out of it later so i can run the installing command of install.wim). Am i doing it right so far?

**Comment by Icesito68** [comment]
I did not select it, I do not know if there will be a problem, but yes, you have to extract the .img in a folder in the download section

**Comment by ahmeda9a** [comment]
Alright, i will test it. I will tell you the results.

**Comment by Icesito68** [comment]
Ok, good luck

**Comment by ahmeda9a** [comment]
I get an error when trying to start parted using
 Parted /dev/block/sda
It says: 
/system/bin/sh: parted: inaccessible or not found.
![Screenshot 2022-10-13 121154](https://user-images.githubusercontent.com/9741161/195570277-27607104-ddd9-4970-bed7-ad9fbc4bf325.png)

**Comment by Icesito68** [comment]
because you have not passed parted to the sdcard,the command isadb push (move parted to terminal) /sdcard

**Comment by ahmeda9a** [comment]
I already did that, its not visible in the screenshot because i tried multiple times after pushing it to /sdcard

**Comment by Icesito68** [comment]
do you have the mobile in twrp?

**Comment by ahmeda9a** [comment]
Yes

**Comment by Icesito68** [comment]
it's quite strange what happens

**Comment by ahmeda9a** [comment]
I have used the file manager to make sure that parted was already pushed into /sdcard

**Comment by ahmeda9a** [comment]
Do i need to mount any partitions?
Am i supposed to not decrypt data?

**Comment by Icesito68** [comment]
I did it with encrypted storage, however if it is encrypted by password you must decrypt

**Comment by drtino7** [comment]
try without the mayus on the "P"

**Comment by Icesito68** [comment]
maybe that's a good idea

**Comment by halal-beef** [comment]
incorrect usage, please use

cd /sdcard
chmod 755 parted
./parted /dev/block/sda

**Comment by ahmeda9a** [comment]
Starting from which command?

**Comment by Icesito68** [comment]
I think it's from shell, but I'm not sure, I used the others

**Comment by ahmeda9a** [comment]
Alright, will test them today and report the results early tomorrow

**Comment by Icesito68** [comment]
Ok, good luck

**Comment by ahmeda9a** [comment]
![Screenshot 2022-10-14 123812](https://user-images.githubusercontent.com/9741161/195827731-95bc0d84-a256-49cb-b30f-ca242c3eae73.png)
am i doing this right?

**Comment by ahmeda9a** [comment]
![Screenshot 2022-10-14 125049](https://user-images.githubusercontent.com/9741161/195829915-c87cade3-c651-4ef5-9074-d99086a9c028.png)
i have restarted to twrp then ran the whole thing except rm 28. i got this message

**Comment by Icesito68** [comment]
inside parted write "p" to see if everything is ok, it is normal that the error

**Comment by ahmeda9a** [comment]
nevermind. i found the solution
but  now im stuck on formating partitions

**Comment by ahmeda9a** [comment]
![Screenshot 2022-10-14 132425](https://user-images.githubusercontent.com/9741161/195835632-36106ca0-e5f4-4aef-81ca-7bec7c58d7d3.png)

**Comment by ahmeda9a** [comment]
why is it happening?

**Comment by Icesito68** [comment]
It doesn't matter, don't format them, delete them from wipe in twrp

**Comment by Icesito68** [comment]
and formatting has to be inside shell

**Comment by ahmeda9a** [comment]
they dont appear in twrp
but i will try starting shell

**Comment by Icesito68** [comment]
format is from shell and android is formatted from wipe typing yes

**Comment by ahmeda9a** [comment]
alright

**Comment by ahmeda9a** [comment]
rebooting to android
it bootted. lets go

**Comment by Icesito68** [comment]
Fine,good luck for the ende of the process

**Comment by halal-beef** [comment]
You didn't do the commands in adb shell and it does matter

**Comment by Icesito68** [comment]
I thought that the truth worked, but that's it, you have to do it in shell

**Comment by ahmeda9a** [comment]
i did it correctly and windows is almost installed
next is drivers

**Comment by ahmeda9a** [comment]
windows 11 booted successfully!

**Comment by ahmeda9a** [comment]
> When i downloaded windows arm, i chose the option to "include updates" then ran the script. The result was an ISO file(which i will extract the files out of it later so i can run the installing command of install.wim). Am i doing it right so far?

and yes. you can install a windows version that has updates included.
